---
title: "Water Chemistry Script"
format: html
editor: visual
author: Hailey Veirs, Meagan Brown, Michael Zargari, Erica Dale
execute: 
  echo: true
  warning: false
  message: false
---

## Installing packages

```{r}
## install.packages("metajam")
## install.packages("tidyverse")
## install.packages("here")
## install.packages("janitor")
## install.packages("lubridate")
## install.packages("patchwork")
```

## Loading libraries

```{r}
## Importing data directly from website
library(metajam)

## Used to tidy/clean up data and create beautiful ggplots
library(tidyverse)

## Helps us get to file paths
library(here)

## Cleans up column names
library(janitor)

## Easy dating
library(lubridate)

## Combining plots side by side
library(patchwork)
```

## Pseudo Code (First draft)

```{r}
## Read in Q1, Q2, Q3, RMP data sets
## Merge the 4 data sets by date
## Clean names
## Pivot longer
## Select for NO3- (Nitrate) and K (Potassium)
## Group by site
## ggplot for Potassium
## ggplot for Nitrate
## add ggplots together using divide (potassium/nitrate)
```

## Reading in the raw data

```{r}
## Read in the data using metajam:

raw_BQ1 <- metajam::read_d1_files(
  folder_path = "/courses/EDS214/threeza-crowd/__QuebradaCuenca1-Bisley__csv", 
  fnc = "read_csv")

raw_BQ2 <- metajam::read_d1_files(
  folder_path = "/courses/EDS214/threeza-crowd/__QuebradaCuenca2-Bisley__csv", 
  fnc = "read_csv")

raw_BQ3 <- metajam::read_d1_files(
  folder_path = "/courses/EDS214/threeza-crowd/__QuebradaCuenca3-Bisley__csv", 
  fnc = "read_csv")

raw_PRM <- metajam::read_d1_files(
  folder_path = "/courses/EDS214/threeza-crowd/__RioMameyesPuenteRoto__csv", 
  fnc = "read_csv")

## Save the data frames from each site data set as the initial data frame for each

raw_BQ1 <- raw_BQ1$data
raw_BQ2 <- raw_BQ2$data
raw_BQ3 <- raw_BQ3$data
raw_PRM <- raw_PRM$data
```

## Cleaning the data

### The code below gives us a standard naming convention by making all titles lowercase and formatting special characters

```{r}
bq1 <- raw_BQ1 %>% 
  clean_names()

bq2 <- raw_BQ2 %>% 
  clean_names()

bq3 <- raw_BQ3 %>% 
  clean_names()

prm <- raw_PRM %>%
  clean_names()
```

## Combine the rows

```{r}
## We are stacking the data to match the datasets by the column names. 
joined_data <- bind_rows(bq1, bq2, bq3, prm)

## Select to keep rows: sample_id, sample_date, no3_n, k
## We also are plotting the values by month so we standardized all dates to fall on the first of every month
stream_quality <- joined_data %>%
  select(sample_id, sample_date, no3_n, k) %>% 
  mutate(year = year(sample_date),
         date = ymd(paste0(year, "-", month(sample_date), "-1"))) %>% 
  filter(year %in% 1988:1994) 

## We are summarizing the data to get the mean of each of our variables (nitrate and potassium)
monthly_quality <- stream_quality %>% 
  group_by(sample_id, date) %>%  
  summarize(monthlyno3 = mean(no3_n, na.rm = TRUE),
            monthlyk = mean(k, na.rm = TRUE))
```

## Creating our first graph

```{r}
## Test comment
monthlyno3graph <- ggplot(monthly_quality, 
                          aes(x = date, 
                              y = monthlyno3)) +
  geom_line(aes(color = sample_id)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  labs(x = "Year",
       y = "K mg")

monthlykgraph <- ggplot(monthly_quality, 
                        aes(x = date, 
                            y = monthlyk)) +
  geom_line(aes(color = sample_id)) +
  theme_classic() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  labs(x = "Year",
       y = "N03-N ug")
  


monthlykgraph / monthlyno3graph
```

## Workflow

```{r}
# stream_explore <- joined_data %>%
#   select(sample_id, sample_date, p_h, si_o2, temp) %>% 
#   mutate(year = year(sample_date),
#          date = ymd(paste0(year, "-", month(sample_date), "-1"))) %>% 
#   filter(year %in% 2007:2009) 
# 
# monthly_explore <- stream_explore %>% 
#   group_by(sample_id, date) %>%  
#   summarize(p_h = mean(p_h, na.rm = TRUE),
#             temp = mean(temp, na.rm = TRUE)) %>% 
#   pivot_longer(cols = p_h:temp, 
#                names_to = "indicator", 
#                values_to = "value")
# 
# ggplot(data = monthly_explore,
#        aes(x= date,
#            y = value)) +
#   geom_line() +
#   facet_wrap(~indicator,scales = "free")
# 
# # temp <- monthly_explore %>% 
# #   filter(indicator %in% c("temp"))
# #          
# # ph_only <- monthly_explore %>% 
# #   filter(indicator == "p_h")
# # 
# # ph <- ggplot(data = ph_only,
# #        aes(x = date,
# #            y = value)) +
# #   geom_line()
# # 
# # tempplot <- ggplot(temp,
# #        aes(x = date,
# #            y = value,
# #            color = indicator)) +
# #   geom_line()
# # 
# # tempplot / ph
# 
```

Sentiments vs temp

```{r}

stream_explore <- joined_data %>%
  select(sample_id, sample_date, temp) %>% 
  mutate(year = year(sample_date),
         date = ymd(paste0(year, "-", month(sample_date), "-1"))) %>% 
  filter(year %in% 2010:2018) 

monthly_explore <- stream_explore %>% 
  group_by(sample_id, date) %>%  
  summarize(temp = min(temp))

temp_plot <- ggplot(data = monthly_explore,
       aes(x = date,
           y = temp)) +
  geom_point(aes(color = sample_id)) +
  geom_smooth(method = lm, se = FALSE, col = 'red', size = 1) +
  theme_minimal() +
  facet_wrap(~sample_id) +
  theme(legend.position = "none",
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black")) +
  labs(x = "Year",
       y = "Temperature (Celsius)")

temp_plot
```
